const API_URL = "http://localhost:3000/api";

const $ = x => document.getElementById(x);

// --- TRANSLATIONS DICTIONARY ---
const TRANSLATIONS = {
  en: {
    logo_title: "🏢 AgriQueue",
    staff_portal: "STAFF",
    staff_control: "STAFF CONTROL",
    staff_login: "Staff Login",
    login_sub: "Access live farmer applications, queue listings, and update procurement statuses.",
    username_lbl: "Username",
    pass_lbl: "Password",
    login_btn: "Enter Staff Dashboard",
    demo_creds: "Demo Credentials:",
    logout_btn: "Logout",
    
    // Dashboard
    stats_tag: "CENTRE WORKFLOW CONTROL",
    dash_title: "Live Procurement Queue",
    dash_desc: "Real-time list of farmer bookings. Manage queue order, call farmers, and process payments.",
    refresh_btn: "↻ Refresh Data",
    
    // Stats
    stat_farmers: "REGISTERED FARMERS",
    stat_apps: "TOTAL APPLICATIONS",
    stat_waiting: "LIVE WAITING QUEUE",
    stat_arrived: "ARRIVED AT CENTRE",
    stat_served: "SERVED & PAID",
    
    // Filters
    filter_centre: "Select Centre",
    filter_date: "Filter Date",
    live_monitor: "LIVE MONITOR • Auto refreshing every 5 seconds",
    active_queue: "Active Procurement Queue",
    
    // Table Headers
    th_queue: "QUEUE #",
    th_farmer: "FARMER DETAILS",
    th_app_id: "APPLICATION ID",
    th_time: "TIME SLOT",
    th_crop_qty: "CROP & QTY",
    th_status: "STATUS",
    th_priority: "PRIORITY STATUS",
    th_actions: "ACTIONS",
    
    // Table Actions
    btn_call: "📢 Call",
    btn_weighed: "Weighed",
    btn_graded: "Graded",
    btn_paid: "💰 Paid",
    
    // Activity Log
    recent_events: "RECENT EVENTS",
    activity_title: "Recent Activity & Mock SMS Logs",
    activity_desc: "Chronological list of all SMS notifications generated by the system.",
    
    // Placeholders
    placeholder_user: "Enter username",
    placeholder_pass: "Enter password"
  },
  kn: {
    logo_title: "🏢 ಅಗ್ರಿಕ್ಯೂ (AgriQueue)",
    staff_portal: "ಸಿಬ್ಬಂದಿ",
    staff_control: "ಸಿಬ್ಬಂದಿ ನಿಯಂತ್ರಣ",
    staff_login: "ಸಿಬ್ಬಂದಿ ಲಾಗಿನ್",
    login_sub: "ರೈತರ ಸಕ್ರಿಯ ಅರ್ಜಿಗಳು, ಕ್ಯೂ ಪಟ್ಟಿಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಮತ್ತು ಖರೀದಿ ಸ್ಥಿತಿಯನ್ನು ನವೀಕರಿಸಲು ಪ್ರವೇಶಿಸಿ.",
    username_lbl: "ಬಳಕೆದಾರ ಹೆಸರು",
    pass_lbl: "ಪಾಸ್‌ವರ್ಡ್",
    login_btn: "ಸಿಬ್ಬಂದಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಿಸಿ",
    demo_creds: "ಡೆಮೊ ರುಜುವಾತುಗಳು:",
    logout_btn: "ಲಾಗ್ ಔಟ್",
    
    // Dashboard
    stats_tag: "ಕೇಂದ್ರದ ಕಾರ್ಯವೈಖರಿ ನಿಯಂತ್ರಣ",
    dash_title: "ಲೈವ್ ಖರೀದಿ ಕ್ಯೂ (Queue)",
    dash_desc: "ರೈತರ ಬುಕಿಂಗ್‌ಗಳ ನೈಜ-ಸಮಯದ ಪಟ್ಟಿ. ಕ್ಯೂ ಕ್ರಮವನ್ನು ನಿರ್ವಹಿಸಿ, ರೈತರನ್ನು ಕರೆ ಮಾಡಿ ಮತ್ತು ಪಾವತಿಗಳನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿ.",
    refresh_btn: "↻ ಡೇಟಾ ನವೀಕರಿಸಿ",
    
    // Stats
    stat_farmers: "ನೋಂದಾಯಿತ ರೈತರು",
    stat_apps: "ಒಟ್ಟು ಅರ್ಜಿಗಳು",
    stat_waiting: "ಸಕ್ರಿಯ ಕಾಯುವ ಕ್ಯೂ",
    stat_arrived: "ಕೇಂದ್ರಕ್ಕೆ ಆಗಮಿಸಿದವರು",
    stat_served: "ಖರೀದಿ ಮತ್ತು ಪಾವತಿ ಪೂರ್ಣ",
    
    // Filters
    filter_centre: "ಖರೀದಿ ಕೇಂದ್ರ ಆಯ್ಕೆಮಾಡಿ",
    filter_date: "ದಿನಾಂಕ ಫಿಲ್ಟರ್",
    live_monitor: "ಲೈವ್ ಮಾನಿಟರ್ • ಪ್ರತಿ 5 ಸೆಕೆಂಡಿಗೆ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ನವೀಕರಣಗೊಳ್ಳುತ್ತದೆ",
    active_queue: "ಸಕ್ರಿಯ ಖರೀದಿ ಕ್ಯೂ (Queue)",
    
    // Table Headers
    th_queue: "ಕ್ಯೂ ಸಂಖ್ಯೆ",
    th_farmer: "ರೈತರ ವಿವರಗಳು",
    th_app_id: "ಅರ್ಜಿ ಐಡಿ",
    th_time: "ಸಮಯದ ಸ್ಲಾಟ್",
    th_crop_qty: "ಬೆಳೆ ಮತ್ತು ಪ್ರಮಾಣ",
    th_status: "ಸ್ಥಿತಿ",
    th_priority: "ಆದ್ಯತೆಯ ಸ್ಥಿತಿ",
    th_actions: "ಕ್ರಮಗಳು",
    
    // Table Actions
    btn_call: "📢 ಕರೆ ಮಾಡಿ",
    btn_weighed: "ತೂಕ ಮಾಡಲಾಗಿದೆ",
    btn_graded: "ಗ್ರೇಡಿಂಗ್ ಮಾಡಲಾಗಿದೆ",
    btn_paid: "💰 ಪಾವತಿಸಲಾಗಿದೆ",
    
    // Activity Log
    recent_events: "ಇತ್ತೀಚಿನ ಈವೆಂಟ್‌ಗಳು",
    activity_title: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ ಮತ್ತು ಮಾದರಿ ಎಸ್ಎಂಎಸ್ ಲಾಗ್",
    activity_desc: "ವ್ಯವಸ್ಥೆಯಿಂದ ರಚಿಸಲಾದ ಎಲ್ಲಾ ಎಸ್ಎಂಎಸ್ ಅಧಿಸೂಚನೆಗಳ ಕಾಲಾನುಕ್ರಮದ ಪಟ್ಟಿ.",
    
    // Placeholders
    placeholder_user: "ಬಳಕೆದಾರ ಹೆಸರು ನಮೂದಿಸಿ",
    placeholder_pass: "ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ"
  },
  hi: {
    logo_title: "🏢 एग्रीक्यू (AgriQueue)",
    staff_portal: "कर्मचारी",
    staff_control: "कर्मचारी नियंत्रण",
    staff_login: "कर्मचारी लॉगिन",
    login_sub: "किसान के लाइव आवेदनों, कतार सूचियों तक पहुँचें, और खरीद स्थिति अपडेट करें.",
    username_lbl: "उपयोगकर्ता नाम",
    pass_lbl: "पासवर्ड",
    login_btn: "कर्मचारी डैशबोर्ड में प्रवेश करें",
    demo_creds: "डेमो क्रेडेंशियल:",
    logout_btn: "लॉग आउट",
    
    // Dashboard
    stats_tag: "केंद्र कार्यप्रवाह नियंत्रण",
    dash_title: "लाइव खरीद कतार (Queue)",
    dash_desc: "किसान बुकिंग की वास्तविक समय सूची. कतार क्रम प्रबंधित करें, किसानों को बुलाएं और भुगतान संसाधित करें.",
    refresh_btn: "↻ डेटा रीफ्रेश करें",
    
    // Stats
    stat_farmers: "पंजीकृत किसान",
    stat_apps: "कुल आवेदन",
    stat_waiting: "सक्रिय प्रतीक्षा कतार",
    stat_arrived: "केंद्र पर पहुंचे",
    stat_served: "संतुष्ट और भुगतान पूर्ण",
    
    // Filters
    filter_centre: "केंद्र चुनें",
    filter_date: "दिनांक फ़िल्टर",
    live_monitor: "लाइव मॉनिटर • हर 5 सेकंड में स्वचालित रूप से रीफ्रेश होता है",
    active_queue: "सक्रिय खरीद कतार (Queue)",
    
    // Table Headers
    th_queue: "कतार #",
    th_farmer: "किसान का विवरण",
    th_app_id: "आवेदन आईडी",
    th_time: "समय स्लॉट",
    th_crop_qty: "फसल और मात्रा",
    th_status: "स्थिति",
    th_priority: "प्राथमिकता स्थिति",
    th_actions: "कार्रवाई",
    
    // Table Actions
    btn_call: "📢 बुलाएं",
    btn_weighed: "तौला गया",
    btn_graded: "ग्रेडिंग की गई",
    btn_paid: "💰 भुगतान पूर्ण",
    
    // Activity Log
    recent_events: "हाल की घटनाएं",
    activity_title: "हाल की गतिविधि और मॉक एसएमएस लॉग",
    activity_desc: "प्रणाली द्वारा उत्पन्न सभी एसएमएस सूचनाओं की कालानुक्रमिक सूची.",
    
    // Placeholders
    placeholder_user: "उपयोगकर्ता नाम दर्ज करें",
    placeholder_pass: "पासवर्ड दर्ज करें"
  }
};

let currentLang = localStorage.getItem("staffLang") || "en";

// --- DYNAMIC TRANSLATION ENGINE ---
function applyLanguage() {
  const dictionary = TRANSLATIONS[currentLang];
  if (!dictionary) return;
  
  const langSelect = $("langSelect");
  if (langSelect) {
    langSelect.value = currentLang;
  }
  
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (dictionary[key] !== undefined) {
      el.textContent = dictionary[key];
    }
  });
  
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.getAttribute("data-i18n-placeholder");
    if (dictionary[key] !== undefined) {
      el.placeholder = dictionary[key];
    }
  });
}

function changeLanguage(lang) {
  if (TRANSLATIONS[lang]) {
    currentLang = lang;
    localStorage.setItem("staffLang", lang);
    applyLanguage();
    
    // Refresh table and feeds to translate tabular components dynamically
    if ($("staffDashboard")) {
      loadAll();
    }
  }
}

// Bind changeLanguage to window object so inline event handlers work
window.changeLanguage = changeLanguage;

// PAGE ROUTING & DOM INITIALIZATION
document.addEventListener("DOMContentLoaded", () => {
  applyLanguage();
  
  const langSelect = $("langSelect");
  if (langSelect) {
    langSelect.addEventListener("change", (e) => {
      changeLanguage(e.target.value);
    });
  }

  if ($("loginForm")) {
    initLogin();
  }
  if ($("staffDashboard")) {
    initDashboard();
  }
});

// --------------------------------------------------
// STAFF LOGIN PAGE
// --------------------------------------------------
function initLogin() {
  $("loginForm").onsubmit = async (e) => {
    e.preventDefault();
    const username = $("username").value;
    const password = $("password").value;
    const msgDiv = $("msg");
    
    try {
      const r = await fetch(`${API_URL}/staff/login`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, password })
      });
      const d = await r.json();
      
      if (!r.ok) {
        msgDiv.innerHTML = `<div class="error">${d.message}</div>`;
        return;
      }
      
      sessionStorage.setItem("staff", "1");
      msgDiv.innerHTML = `<div class="success">Login successful! Redirecting...</div>`;
      setTimeout(() => {
        location.href = "staff-dashboard.html";
      }, 800);
    } catch (err) {
      msgDiv.innerHTML = `<div class="error">Unable to connect to backend server.</div>`;
    }
  };
}

// --------------------------------------------------
// STAFF DASHBOARD PAGE
// --------------------------------------------------
let knownApplicationIds = new Set();
let isInitialLoad = true;

function initDashboard() {
  if (sessionStorage.getItem("staff") !== "1") {
    location.href = "staff-login.html";
    return;
  }
  
  // Set date input to today
  $("date").value = new Date().toISOString().slice(0, 10);
  
  // Bind events
  $("centre").onchange = loadAll;
  $("date").onchange = loadAll;
  $("btnRefresh").onclick = loadAll;
  
  $("btnLogout").onclick = () => {
    sessionStorage.removeItem("staff");
    location.href = "staff-login.html";
  };
  
  // Initial loads
  loadAll();
  
  // Auto refresh stats, queue, feed every 5 seconds
  setInterval(() => {
    loadAll();
  }, 5000);
}

async function loadAll() {
  await Promise.all([
    loadStats(),
    loadQueue(),
    loadActivityFeed()
  ]);
}

async function loadStats() {
  try {
    const r = await fetch(`${API_URL}/staff/stats`);
    const d = await r.json();
    if (r.ok) {
      $("farmers").textContent = d.farmers;
      $("applications").textContent = d.applications;
      $("waiting").textContent = d.waiting;
      $("served").textContent = d.served;
      $("arrived").textContent = d.arrived;
    }
  } catch (err) {
    console.error("Error loading stats", err);
  }
}

// Translate dynamic status values for table
function getTranslatedStatus(status) {
  const keyMap = {
    "Slot Booked": "status_booked",
    "Arrived": "status_arrived",
    "Produce Weighed": "status_weighed",
    "Produce Graded": "status_graded",
    "Payment Processed": "status_paid",
    "Cancelled": "status_cancelled"
  };
  const key = keyMap[status];
  // Re-use keys from Farmer translations if possible, otherwise use local mapping
  const localMap = {
    "Slot Booked": { en: "Slot Booked", kn: "ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಲಾಗಿದೆ", hi: "स्लॉट बुक किया गया" },
    "Arrived": { en: "Arrived", kn: "ಆಗಮಿಸಲಾಗಿದೆ", hi: "पहुंच गए" },
    "Produce Weighed": { en: "Produce Weighed", kn: "ತೂಕ ಮಾಡಲಾಗಿದೆ", hi: "उपज तौली गई" },
    "Produce Graded": { en: "Produce Graded", kn: "ಗ್ರೇಡಿಂಗ್ ಮಾಡಲಾಗಿದೆ", hi: "ग्रेडिंग की गई" },
    "Payment Processed": { en: "Payment Processed", kn: "ಪಾವತಿ ಪೂರ್ಣಗೊಂಡಿದೆ", hi: "भुगतान संसाधित" },
    "Cancelled": { en: "Cancelled", kn: "ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ", hi: "रद्द किया गया" }
  };
  return localMap[status] ? localMap[status][currentLang] : status;
}

async function loadQueue() {
  const centre = $("centre").value;
  const date = $("date").value;
  if (!date) return;
  
  const dictionary = TRANSLATIONS[currentLang];
  
  try {
    const r = await fetch(`${API_URL}/staff/applications?centre=${encodeURIComponent(centre)}&date=${date}`);
    const applications = await r.json();
    
    if (!r.ok) {
      $("table").innerHTML = `<div class="error">Error loading queue data.</div>`;
      return;
    }
    
    // Check for new applications (added while dashboard is open)
    const currentIds = new Set(applications.map(app => app.id));
    if (!isInitialLoad) {
      for (const app of applications) {
        if (!knownApplicationIds.has(app.id)) {
          showNewApplicationBanner(app);
        }
      }
    }
    knownApplicationIds = currentIds;
    isInitialLoad = false;
    
    // Render applications table
    const tableDiv = $("table");
    if (!applications || applications.length === 0) {
      tableDiv.innerHTML = `<div class="empty">No live active applications for this centre/date. When a farmer books a slot, it will appear here.</div>`;
      return;
    }
    
    tableDiv.innerHTML = `
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>${dictionary.th_queue}</th>
              <th>${dictionary.th_farmer}</th>
              <th>${dictionary.th_app_id}</th>
              <th>${dictionary.th_time}</th>
              <th>${dictionary.th_crop_qty}</th>
              <th>${dictionary.th_status}</th>
              <th>${dictionary.th_priority}</th>
              <th>${dictionary.th_actions}</th>
            </tr>
          </thead>
          <tbody>
            ${applications.map(b => {
              // Classify priority styles
              let prioClass = "priority-normal";
              if (b.priorityScore === 3) prioClass = "priority-high";
              else if (b.priorityScore === 2) prioClass = "";
              
              // Set up status pills
              let statusPillColor = "#e9f2ff";
              let statusTextColor = "#285f9b";
              if (b.status === "Arrived") {
                statusPillColor = "#fef9c3";
                statusTextColor = "#854d0e";
              } else if (b.status === "Produce Weighed") {
                statusPillColor = "#dbeafe";
                statusTextColor = "#1e40af";
              } else if (b.status === "Produce Graded") {
                statusPillColor = "#f3e8ff";
                statusTextColor = "#6b21a8";
              }
              
              return `
                <tr>
                  <td>
                    <strong class="q">#${b.queuePosition}</strong>
                    <small>~${b.estimatedWait} min wait</small>
                  </td>
                  <td>
                    <b>${b.farmerName}</b>
                    <small>ID: ${b.farmerId}</small>
                    <small>Ph: ${b.phone}</small>
                  </td>
                  <td>
                    <b>${b.id}</b>
                    <small>${b.centre}</small>
                  </td>
                  <td>
                    <b>${b.slot}</b>
                    <small>Date: ${b.date}</small>
                  </td>
                  <td>
                    <b>${b.crop || "—"}</b>
                    <small>${b.quantity || 0} kg</small>
                  </td>
                  <td>
                    <span class="pill" style="background: ${statusPillColor}; color: ${statusTextColor};">
                      ${getTranslatedStatus(b.status)}
                    </span>
                  </td>
                  <td>
                    <span class="priority-badge ${prioClass}">
                      ${b.priorityReason}
                    </span>
                  </td>
                  <td>
                    <div class="actions">
                      ${b.status === "Slot Booked" ? `
                        <button class="btn-call" onclick="callFarmer('${b.id}')">${dictionary.btn_call}</button>
                      ` : ''}
                      
                      ${b.status === "Arrived" ? `
                        <button onclick="updateStatus('${b.id}', 'Produce Weighed')">${dictionary.btn_weighed}</button>
                      ` : ''}
                      
                      ${b.status === "Produce Weighed" ? `
                        <button onclick="updateStatus('${b.id}', 'Produce Graded')">${dictionary.btn_graded}</button>
                      ` : ''}
                      
                      ${b.status === "Produce Graded" ? `
                        <button class="btn-pay" onclick="updateStatus('${b.id}', 'Payment Processed')">${dictionary.btn_paid}</button>
                      ` : ''}
                    </div>
                  </td>
                </tr>
              `;
            }).join("")}
          </tbody>
        </table>
      </div>
    `;
  } catch (err) {
    console.error("Error loading queue", err);
  }
}

async function loadActivityFeed() {
  try {
    const r = await fetch(`${API_URL}/staff/notifications`);
    const notifications = await r.json();
    const feedDiv = $("feed");
    
    if (!r.ok || !notifications || notifications.length === 0) {
      feedDiv.innerHTML = `<div class="empty">No events in the activity feed.</div>`;
      return;
    }
    
    feedDiv.innerHTML = notifications.slice(0, 10).map(n => `
      <div class="feed">
        <b>📱 SMS MOCK</b>
        <span>Phone: ${n.phone}</span>
        <p>${n.message}</p>
        <small>${new Date(n.createdAt).toLocaleTimeString()}</small>
      </div>
    `).join("");
  } catch (err) {
    console.error("Error loading activity feed", err);
  }
}

function showNewApplicationBanner(app) {
  const container = $("alertBannerContainer");
  
  if ($(`banner_${app.id}`)) return;
  
  const banner = document.createElement("div");
  banner.id = `banner_${app.id}`;
  banner.className = "notification-banner";
  banner.innerHTML = `
    <div>
      <strong>✨ NEW APPLICATION RECEIVED:</strong>
      Farmer <b>${app.farmerName}</b> | 
      Application: <b>${app.id}</b> | 
      Slot: <b>${app.slot}</b> | 
      Queue: <b>#${app.queuePosition}</b> | 
      Crop: <b>${app.crop || '—'}</b> (${app.quantity || 0} kg) | 
      Status: <span class="pill" style="background:#e0f2fe;color:#0369a1;padding:2px 6px;font-size:9px">${getTranslatedStatus(app.status)}</span>
    </div>
    <button onclick="this.parentElement.remove()" style="margin-left: 20px;">Dismiss</button>
  `;
  container.appendChild(banner);
  
  setTimeout(() => {
    if (banner && banner.parentElement) {
      banner.remove();
    }
  }, 15000);
}

async function callFarmer(bookingId) {
  try {
    const r = await fetch(`${API_URL}/staff/applications/${bookingId}/call`, {
      method: "PUT"
    });
    const d = await r.json();
    alert(d.message);
    loadAll();
  } catch (err) {
    alert("Failed to call farmer.");
  }
}

async function updateStatus(bookingId, status) {
  try {
    const r = await fetch(`${API_URL}/staff/applications/${bookingId}/status`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status })
    });
    const d = await r.json();
    
    if (!r.ok) {
      alert(d.message);
      return;
    }
    
    loadAll();
  } catch (err) {
    alert("Failed to update status.");
  }
}

// Bind methods to window so inline event handlers work
window.callFarmer = callFarmer;
window.updateStatus = updateStatus;
